// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ietvlucbytchkgmutypl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldHZsdWNieXRjaGtnbXV0eXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTg3MjEsImV4cCI6MjA2MjYzNDcyMX0.kVgMoaKN-AFD6ScehJ4o3BbzTVZ9yovgWqhJgSUTJBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);